repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        exclude: ^flash/
        args: [--py311-plus]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args:
          - --safe
          - --quiet

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.7.0
          - pydocstyle==6.3.0
          - flake8-bugbear==23.9.16
          - flake8-comprehensions==3.14.0
          - flake8_2020==1.8.1
          - mccabe==0.7.0
          - pycodestyle==2.11.0
          - pyflakes==3.1.0
          - flake8-return==1.2.0
          - flake8-sfs==0.0.4
          - flake8-tuple==0.4.1
          - flake8-async==22.11.14
          - flake8-pbp==1.0.13

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        args:
          - --fix
