name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Test with tox
      run: tox $(test "$RUNNER_DEBUG" && echo "-vv -- -vv")
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: ${{ matrix.python-version }}

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coverage
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
